services:

  frontend:
    env-file:
      - .env.dev
    volumes:
      - ./frontend:/app
      - node_modules: /app/node_modules
    command: npm run dev

  backend:
    command: uvicorn app.main.app --host 0.0.0.0 --port ${PORT} ${DEBUG:+--reload}
    env-file:
      - .env.dev
    volumes:
      - ./backend:/app

  volumes:
    node_modules:

