"""Initial migration

Revision ID: 8ad93622a2f9
Revises: 
Create Date: 2025-08-20 10:43:13.934877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ad93622a2f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id_etudiant'), table_name='etudiants')
    op.drop_table('etudiants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etudiants',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_etudiant', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date_creation', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('sexe', mysql.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_etudiant'), 'etudiants', ['id_etudiant'], unique=True)
    # ### end Alembic commands ###
