"""initial

Revision ID: 381baac30c1d
Revises: 
Create Date: 2025-08-29 17:58:17.313160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381baac30c1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_etudiant', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('lieu_naissance', sa.String(length=100), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=False),
    sa.Column('nationalite', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('nom_parent_tuteur', sa.String(length=100), nullable=True),
    sa.Column('telephone_parent_tuteur', sa.String(length=20), nullable=True),
    sa.Column('adresse_parent_tuteur', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('date_inscription', sa.Date(), server_default=sa.text('(current_date())'), nullable=True),
    sa.Column('classe_actuelle_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etudiants_date_naissance'), 'etudiants', ['date_naissance'], unique=False)
    op.create_index(op.f('ix_etudiants_email'), 'etudiants', ['email'], unique=True)
    op.create_index(op.f('ix_etudiants_id'), 'etudiants', ['id'], unique=False)
    op.create_index(op.f('ix_etudiants_id_etudiant'), 'etudiants', ['id_etudiant'], unique=True)
    op.create_index(op.f('ix_etudiants_lieu_naissance'), 'etudiants', ['lieu_naissance'], unique=False)
    op.create_index(op.f('ix_etudiants_nom'), 'etudiants', ['nom'], unique=False)
    op.create_index(op.f('ix_etudiants_prenom'), 'etudiants', ['prenom'], unique=False)
    op.create_index(op.f('ix_etudiants_sexe'), 'etudiants', ['sexe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etudiants_sexe'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_prenom'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_nom'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_lieu_naissance'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_id_etudiant'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_id'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_email'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_date_naissance'), table_name='etudiants')
    op.drop_table('etudiants')
    # ### end Alembic commands ###
