name: Auto commit change

on:
  pull_request:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.13


      - name: Configure Git
        run: |
          git config user.name 'tresor-del'
          git config user.email 'tresoradzanto7@gmail.com'

      - name: Create and activate venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
        shell: bash


      - name: Install uv
        run: |
          source .venv/bin/activate
          curl -LsSf https://astral.sh/uv/install.sh | sh
        shell: bash


      - name: Sync dependencies
        run: |
          source .venv/bin/activate
          uv sync --project ./backend
        shell: bash

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest ./backend
        shell: bash
